# Default values for banking-web-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: manjunathachar/banking-web-app
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: "banking-web-app"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "banking-web-app-sa"

podAnnotations: {}

podLabels: 
  app: banking-web-app
  version: v1

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

# Essential environment variables only
env:
  - name: SERVER_PORT
    value: "8083"
  - name: SPRING_PROFILES_ACTIVE
    value: "production"

# Health checks removed - let Kubernetes handle basic container health

service:
  type: LoadBalancer
  port: 8718
  targetPort: 8083
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

ingress:
  enabled: false

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 256m

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector:
  kubernetes.io/os: linux
  role: user

tolerations: []

# Pod affinity removed - using simple node selector instead
